name: vulnerability-scanner
on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [Weekly vulnerability scanner]

jobs:
  vulnerability-scanner:
    name: vulnerability-scanner
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Appcharge/github-actions-warehouse/.github/actions/security/trivy@v0.0.3-trivy
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
